### PR TITLE
converted ENV.fetch() to ENV[]

### PR DESCRIPTION
**Pull request by priom**

### CODE REVIEW

**Comment by janko-m** [comment]
What is the reason for this change? IMO you always want to `ENV.fetch`.

**Comment by priom** [comment]
It doesn't work on CI and production, just had some errors regarding this.

**Comment by sorentwo** [comment]
@priom If you are getting errors in CI and production it means you are lacking the correct environment variables. That would be a big problem for production in particular, as you would get `nil` values for your credentials. All of these examples are required value,s you absolutely should be using `ENV.fetch`.

**Comment by priom** [comment]
btw ENV[] does work for my all other services and in other gems too. And I'm setting production env variables in a separate on Heroku. Anyway thanks.

**Comment by sorentwo** [comment]
Sure, `ENV[]` will get values, but it won't tell you when they are missing. It is only a configuration example in the README, you are welcome to use any configuration style you like.

**Comment by priom** [comment]
Oh actually just remembered it also threw an error in development even though the variables were correctly present. Anyway thanks for the explanations.

**Pull request closed without merging**
